apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: pinit
spec:
  selector:
    app: pinit-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  